services:
  soap-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: soap-server
    working_dir: /usr/app
    volumes:
      - ./:./
  postgres:
    image: postgres:17.2-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ~/database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres